name: Build kernel deb packages
on: workflow_dispatch

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          apt update -y && apt upgrade -y
          apt install -y wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev build-essential libelf-dev libncurses5-dev dwarves 
          apt build-dep -y linux

      - name: Build
        run: |
          bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
