name: Build util-linux
on: workflow_dispatch

jobs:
  build:
    name: Build util-linux
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          bash build_scripts/dep.sh
      - name: Build
        run: |
          bash build_scripts/util-linux.sh

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
